from flask import Flask, render_template, jsonify, request
from flask_cors import CORS
import os

app = Flask(__name__)
CORS(app)

# Configuration
app.config['DEBUG'] = True
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'dev-secret-key')

@app.route('/')
def index():
    """Serve the main page."""
    return render_template('index.html')

@app.route('/api/health')
def health():
    """Health check endpoint."""
    return jsonify({
        'status': 'healthy',
        'message': 'Application is running'
    })

@app.route('/api/data', methods=['GET'])
def get_data():
    """Get sample data."""
    data = {
        'items': [
            {'id': 1, 'name': 'Item 1', 'description': 'First sample item'},
            {'id': 2, 'name': 'Item 2', 'description': 'Second sample item'},
            {'id': 3, 'name': 'Item 3', 'description': 'Third sample item'}
        ],
        'total': 3
    }
    return jsonify(data)

@app.route('/api/data', methods=['POST'])
def create_data():
    """Create new data item."""
    data = request.get_json()
    
    if not data or 'name' not in data:
        return jsonify({'error': 'Name is required'}), 400
    
    # In a real app, you'd save to a database
    response = {
        'id': 4,  # Would be generated by database
        'name': data['name'],
        'description': data.get('description', ''),
        'created': True
    }
    
    return jsonify(response), 201

@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors."""
    return jsonify({'error': 'Not found'}), 404

@app.errorhandler(500)
def internal_error(error):
    """Handle 500 errors."""
    return jsonify({'error': 'Internal server error'}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)